### ISSUE TITLE
number-max-precision leads to odd px values

### ISSUE THREAD

**Issue by fraincs** [gsoft-inc/wl-web-configs#140]
In some situations rounding rem values in CSS leads to non precise values in pixel.

When there's a need for a value with a .5px in rem the value is: 0.03125 which triggers a linting error, rounding to 0.03123 would compute a value of 0.5008px if 1 rem = 16px. This can lead to problematic values when dealing with line-height.

**Comment by patricklafrance** [comment]
Hey @fraincs, thank you for stating a problem but I am not sure what are you looking for with this issue?

**Comment by fraincs** [comment]
Upon further discussion, as the issues arises only a few times, I think it's best to turn off that rule on case by cases basis.
