### ISSUE TITLE
The postcss package reference is incorrect in the readme

### ISSUE THREAD

**Issue by franckgaudin** [gsoft-inc/wl-web-configs#160]
The package name in the readme no longer seems to correspond to the actual package in the repository. 

<img width="385" alt="Capture d’écran, le 2023-10-28 à 16 23 12" src="https://github.com/gsoft-inc/wl-web-configs/assets/2379339/f163e681-fad6-4696-b92d-ac24209e934d">

The expected package name is **@workleap/postcss-configs** and the link is https://github.com/gsoft-inc/wl-web-configs/tree/main/packages/postcss-configs#workleappostcss-configs

**Comment by patricklafrance** [comment]
Oops, will fix next week, thank you!

**Comment by patricklafrance** [comment]
Fixed by https://github.com/gsoft-inc/wl-web-configs/pull/161, thank you 🙏🏻
