### ISSUE TITLE
Update postcss installation procedure to display example of both CJS and ESM

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/wl-web-configs#87]
The current documentation shows what to put in the config: 
```
/** @type {import("postcss").Postcss} */
module.exports = {
```

module.exports is the CJS synthax. It should be 
```
export default {
```

instead.

**Comment by patricklafrance** [comment]
If postcss support ESM why would any projects need the CJS syntax?

Even our older projects should support ESM export syntax. I'm I missing something?

**Comment by patricklafrance** [comment]
Closing for now as it seems stale, feel free to reopen.
