### ISSUE TITLE
Missing dependency `@types/jest` in swc-configs README documentation

### ISSUE THREAD

**Issue by ofrogon** [gsoft-inc/wl-web-configs#88]
In [packages/swc-configs/README.md](https://github.com/workleap/wl-web-configs/blob/main/packages/swc-configs/README.md#jest), `@types/jest` is missing from dependency.

Without it, IDE is missing all Jest types and methods in `.test.js[x]` files.

**Comment by patricklafrance** [comment]
Packages dependencies shouldn’t be typings!

**Comment by ofrogon** [comment]
I'm talking about this secion f the README:
![image](https://github.com/workleap/wl-web-configs/assets/4323800/8f7feccf-083a-432c-adee-31887180bc71)

**Comment by patricklafrance** [comment]
Yeah I don't think it's common practice to add types to installation instructions. I don't recall ever used a package doing this.

The purpose of the installation instructions for the swc configs package is to install the swc configs, not help the user install/setup it's jest environment. That would be the purpose of the installation instruction of the jest package.

**Comment by patricklafrance** [comment]
Closing for now as we don't currently support a jest configuration.
